Repository cloudmarker/cloudmarker, pull requests merged in 2019-05, with the labels that each got.

#117 Set `origin_type` and `alert_worker` for events
  cloudmarker/manager.py
  cloudmarker/workers.py
Labels: improvement

#118 Make mock records similar to real records
  cloudmarker/clouds/mockcloud.py
  cloudmarker/events/mockevent.py
  cloudmarker/util.py
Labels: improvement

#119 Do not alter cloud record in FirewallRuleEvent
  cloudmarker/events/firewallruleevent.py
  cloudmarker/test/test_firewallruleevent.py
Labels: bug

#120 Add audit version to all records
  cloudmarker/manager.py
  cloudmarker/stores/filestore.py
  cloudmarker/test/test_workers.py
  cloudmarker/workers.py
  pylama.ini
Labels: enhancement

#123 Fix 'About' field in email notification for audits
  cloudmarker/manager.py
Labels: bug, improvement

#124 Reuse mock record in AzCloud test setup
  cloudmarker/test/test_azcloud.py
Labels: quality

#125 Update logger format, filename, and backupCount
  Makefile
  cloudmarker/baseconfig.py
Labels: improvement

#130 Add AzVMOSDiskEncryptionEvent plugin
  cloudmarker/events/azvmosdiskencryptionevent.py
  cloudmarker/test/test_azvmosdiskencryptionevent.py
  docs/api/cloudmarker.events.rst
  pylama.ini
Labels: enhancement

#128 Do not let workers crash on plugin errors
  cloudmarker/workers.py
  pylama.ini
Labels: bug

#79 Add detailed documentation for users (Work in progress)
  Makefile
  README.rst
  cloudmarker/__init__.py
  cloudmarker/baseconfig.py
  cloudmarker/manager.py
  docs/api/modules.rst
  docs/conf.py
  docs/index.rst
  docs/tutorial.rst
  pylama.ini
Labels: documentation

#133 Freeze all dependencies for distribution upload
  MANIFEST.in
  Makefile
  cloudmarker/__init__.py
  pkg-requirements.txt
  requirements.txt
  setup.py
  usr-requirements.txt
Labels: improvement

#137 Check only vm_instance_view data in disk plugins
  cloudmarker/events/azvmdatadiskencryptionevent.py
  cloudmarker/events/azvmosdiskencryptionevent.py
  cloudmarker/test/test_azvmdatadiskencryptionevent.py
  cloudmarker/test/test_azvmosdiskencryptionevent.py
Labels: improvement

#131 Add MySQL server to resources evaluated by AzCloud
  cloudmarker/clouds/azcloud.py
  cloudmarker/test/test_azcloud.py
  usr-requirements.txt
Labels: improvement

#141 Add RDBMSEnforceTLSEvent plugin
  cloudmarker/clouds/azcloud.py
  cloudmarker/events/rdbmsenforcetlsevent.py
  cloudmarker/test/test_azcloud.py
  cloudmarker/test/test_rdbmsenforcetlsevent.py
  cloudmarker/util.py
  pylama.ini
Labels: enhancement
