Repository cloudmarker/cloudmarker, pull requests merged in 2019-04, with the labels that each got.

#55 Add EmailStore plugin
  cloudmarker/alerts/emailalert.py
  config.base.yaml
  docs/api/cloudmarker.stores.rst
  pylama.ini
Labels: enhancement

#65 Generate firewall rules with common properties
  cloudmarker/clouds/azurecloud.py
  cloudmarker/clouds/gcpcloud.py
  cloudmarker/test/test_azurecloud.py
  cloudmarker/test/test_gcpcloud.py
  pylama.ini
Labels: enhancement

#68 Add logs in GCPCloud
  cloudmarker/clouds/gcpcloud.py
Labels: improvement

#74 Consistently use the term "record" in AzureCloud
  cloudmarker/clouds/azurecloud.py
Labels: improvement

#73 Add FirewallRuleEvent plugin
  cloudmarker/events/firewallruleevent.py
  cloudmarker/test/test_firewallruleevent.py
  cloudmarker/test/test_util.py
  cloudmarker/util.py
  docs/api/cloudmarker.events.rst
  pylama.ini
Labels: enhancement

#82 Remove emailalert from mockaudit in base config
  config.base.yaml
Labels: bug

#81 Add EsStore plugin
  cloudmarker/stores/esstore.py
  config.base.yaml
  docs/api/cloudmarker.stores.rst
  requirements.txt
Labels: enhancement

#84 Delete venv files after deleting environments
  Makefile
Labels: bug

#85 Generate API docs for cloudmarker.alerts package
  cloudmarker/alerts/__init__.py
  docs/api/cloudmarker.alerts.rst
  docs/api/cloudmarker.rst
Labels: documentation

#87 Rename AzureCloud to AzCloud
  cloudmarker/clouds/azcloud.py
  cloudmarker/test/test_azcloud.py
  docs/api/cloudmarker.clouds.rst
Labels: improvement

#91 Add _max_recs parameter in AzCloud plugin
  cloudmarker/clouds/azcloud.py
Labels: improvement

#90 Search for user configuration in popular locations
  .gitignore
  README.rst
  cloudmarker/__init__.py
  cloudmarker/baseconfig.py
  cloudmarker/manager.py
  cloudmarker/test/test_main.py
  cloudmarker/test/test_util.py
  cloudmarker/util.py
  docs/api/cloudmarker.rst
Labels: enhancement

#75 Add SSL and authentication support in EmailAlert
  cloudmarker/alerts/emailalert.py
  cloudmarker/baseconfig.py
  pylama.ini
Labels: enhancement

#99 Remove EmailAlert configuration from base config
  cloudmarker/baseconfig.py
Labels: improvement

#96 Add tests for SplunkHECStore plugin
  cloudmarker/test/test_splunkhecstore.py
  pylama.ini
Labels: quality

#97 Add tests for EsStore plugin
  cloudmarker/test/test_esstore.py
Labels: quality

#98 Make EmailAlert docs and code consistent
  cloudmarker/alerts/emailalert.py
Labels: documentation

#102 Copy ext from NSG/firewall to firewall rules
  cloudmarker/clouds/azcloud.py
  cloudmarker/clouds/gcpcloud.py
Labels: improvement

#101 Add AzVM plugin
  cloudmarker/clouds/azvm.py
  cloudmarker/util.py
  docs/api/cloudmarker.clouds.rst
Labels: enhancement

#115 Put all plugin configs under a key named 'plugins'
  cloudmarker/baseconfig.py
  cloudmarker/manager.py
Labels: enhancement

#116 Make SplunkHECStore logs detailed and handle empty list of records
  cloudmarker/stores/splunkhecstore.py
  cloudmarker/test/test_splunkhecstore.py
Labels: improvement
