Repository cloudmarker/cloudmarker, pull requests merged in 2019-03, with the labels that each got.

#46 Create raw, ext, and com top-level buckets
  cloudmarker/checks/mockcheck.py
  cloudmarker/clouds/azurecloud.py
  cloudmarker/clouds/gcpcloud.py
  cloudmarker/clouds/mockcloud.py
  cloudmarker/stores/filestore.py
  cloudmarker/stores/mongodbstore.py
  cloudmarker/test/__init__.py
  cloudmarker/test/test_filestore.py
  cloudmarker/test/test_mongodbstore.py
  cloudmarker/test/test_workers.py
  cloudmarker/util.py
  cloudmarker/workers.py
Labels: improvement

#50 Increase logging levels of root logger and adal-python
  config.base.yaml
Labels: improvement

#52 Change: checks to events
  cloudmarker/checks/__init__.py
  cloudmarker/events/__init__.py
  cloudmarker/events/firewallevent.py
  cloudmarker/events/mockevent.py
  cloudmarker/manager.py
  cloudmarker/stores/__init__.py
  cloudmarker/test/test_workers.py
  cloudmarker/workers.py
  config.base.yaml
  docs/api/cloudmarker.events.rst
  docs/api/cloudmarker.rst
Labels: improvement

#54 Add unit tests for GCPCloud
  cloudmarker/test/test_gcpcloud.py
  pylama.ini
Labels: quality

#57 SplunkHECStore plugin
  cloudmarker/stores/splunkhecstore.py
  pylama.ini
Labels: enhancement

#66 Rename _logger to _log in workers
  cloudmarker/workers.py
Labels: refactoring

#59 SlackAlert Plugin
  cloudmarker/alerts/slackalert.py
  config.base.yaml
  pylama.ini
  requirements.txt
Labels: enhancement
