Repository cloudmarker/cloudmarker, pull requests merged in 2019-06, with the labels that each got.

#143 Replace os.rename() with os.replace() in FileStore
  cloudmarker/stores/filestore.py
Labels: improvement

#140 Add PostgresSQL to resources evaluated by AzCloud
  cloudmarker/clouds/azcloud.py
  cloudmarker/test/test_azcloud.py
  pylama.ini
Labels: enhancement

#146 Add baseconfig key for RDBMSEnforceTLSEvent
  cloudmarker/baseconfig.py
Labels: improvement

#147 Instantiate plugins in worker processes
  cloudmarker/manager.py
  cloudmarker/test/test_workers.py
  cloudmarker/workers.py
Labels: bug
