Repository cloudmarker/cloudmarker, pull requests merged in 2019-07, with the labels that each got.

#150 Add AzSQL plugin
  cloudmarker/clouds/azsql.py
  docs/api/cloudmarker.clouds.rst
  docs/api/cloudmarker.events.rst
  pylama.ini
  usr-requirements.txt
Labels: enhancement

#149 Use concurrency in GCPCloud
  cloudmarker/clouds/gcpcloud.py
  cloudmarker/test/test_gcpcloud.py
  cloudmarker/util.py
  pylama.ini
Labels: enhancement

#152 Add AzSQLDatabaseTDEEvent plugin
  cloudmarker/baseconfig.py
  cloudmarker/events/azsqldatabasetdeevent.py
  cloudmarker/test/test_azsqldatabasetdeevent.py
  pylama.ini
Labels: enhancement

#153 Add test cases for AzSQL plugin
  cloudmarker/test/test_azsql.py
Labels: improvement

#154 Add AzWebApp and AzWebAppTLSEvent plugins
  cloudmarker/baseconfig.py
  cloudmarker/clouds/azwebapp.py
  cloudmarker/events/azwebapptlsevent.py
  docs/api/cloudmarker.clouds.rst
  docs/api/cloudmarker.events.rst
  pylama.ini
Labels: enhancement

#161 Make TLS version configurable in AzWebAppTLSEvent
  cloudmarker/events/azwebapptlsevent.py
Labels: bug, improvement

#162 Add test cases for event plugin
  cloudmarker/test/test_azvmdatadiskencryptionevent.py
  cloudmarker/test/test_azvmosdiskencryptionevent.py
Labels: quality

#165 Add AzMonitor plugin
  cloudmarker/clouds/azmonitor.py
  cloudmarker/test/test_azmonitor.py
  pylama.ini
  usr-requirements.txt
Labels: enhancement
